### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hughperkins** [simon-engledew/csharp-netstrings#1]
Nice! License? (e.g. MIT is good :) )

**Comment by hughperkins** [comment]
Oh, you *do* have a license, but in the code. Note that lots of people (myself nearly included) will just move on if it's not in the home page. Like, on the right hand side, many projects show the license, e.g.:

<img width="303" alt="Screen Shot 2022-12-07 at 7 01 03 AM" src="https://user-images.githubusercontent.com/123560/206174419-cc286678-74ad-4820-8a67-1b3d40f46cbd.png">

You can add this by simply adding a `LICENSE` file, e.g. see https://github.com/rj79/pynetstring as an example. (Yes, I'm using netstrings to connect python with c#, so I need a library for both languages :) )

**Comment by simon-engledew** [comment]
Done!

**Comment by hughperkins** [comment]
Great!
